# Generated by Django 6.0.6 on 2026-06-26 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mashina nomi')),
                ('image_url', models.URLField(max_length=500, verbose_name='Rasm URL')),
                ('price', models.CharField(max_length=100, verbose_name="Narxi (so'm)")),
                ('discount_text', models.CharField(blank=True, max_length=200, verbose_name='Chegirma matni')),
                ('has_discount', models.BooleanField(default=False, verbose_name='Chegirmada')),
                ('engine', models.CharField(blank=True, max_length=100, verbose_name='Dvigatel')),
                ('power', models.CharField(blank=True, max_length=100, verbose_name='Quvvat')),
                ('transmission', models.CharField(blank=True, max_length=100, verbose_name='Uzatma')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mashina',
                'verbose_name_plural': 'Mashinalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HighlightCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_title', models.CharField(max_length=100, verbose_name='Tab nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='Mashina')),
            ],
            options={
                'verbose_name': 'Yangilik mashina',
                'verbose_name_plural': 'Yangilik mashinalar',
                'ordering': ['order'],
            },
        ),
    ]
